#ifndef LAYOUT_H
#define LAYOUT_H

#define COMMON_CONTROL_HEIGHT 23
#define DEFAULT_BUTTON_WIDTH 75
#define DIALOG_BOX_MARGINS 11
#define SPACING_BETWEEN_INTERACTIVE_CONTROLS 5
#define SPACING_BETWEEN_LABELS_AND_CONTROLS SPACING_BETWEEN_INTERACTIVE_CONTROLS
#define SPACING_BETWEEN_UNRELATED_CONTROLS DIALOG_BOX_MARGINS
#define SPACING_BETWEEN_BUTTONS 7

BOOL GetAppropriateSize(HWND hWnd, LPSIZE pSize);
void MoveToWorkAreaCenter(HWND hWnd);

#endif // LAYOUT_H
