var name_translate =
{
    "Shendelzare Silkwood": "仙德尔莎·丝木",
    "Abaddon": "亚巴顿",
    "Pugna": "帕格纳",
    "Crixalis": "克里瑟历斯",
    "Clinkz": "克林克兹",
    "Luna Moonfang": "露娜·月痕",
    "Bradwarden": "布兰德瓦登",
    "Zeus": "宙斯 (Merlini)",
    "Aiushtha": "爱由莎",
    "Morphling": "变体精灵",
    "Kardel Sharpeye": "卡德尔·鹰眼",
    "Jah'rakal": "杰拉考",
    "Leviathan": "利维坦",
    "Rhasta": "罗斯塔",
    "Atropos": "阿特洛波丝",
    "Rotund'jere": "罗坦德吉利",
    "Pudge": "胖子",
    "Anub'seran": "阿努伯瑟伦",
    "Mogul Khan": "蒙哥·卡恩",
    "Rylai Crestfall": "莉莱·克丽丝芙",
    "Strygwyr": "史德利古尔",
    "Lucifer": "路西法",
    "Sven": "斯温",
    "Rigwarl": "瑞格沃",
    "Slithice": "司里希丝",
    "Raigor Stonehoof": "瑞格·石蹄",
    "Gondar": "刚铎",
    "Magina": "玛吉纳",
    "Rexxar": "雷克萨",
    "Traxex": "崔希丝",
    "Jakiro": "杰奇洛",
    "Purist Thunderwrath": "普里斯特·雷霆之怒",
    "Razzil Darkbrew": "拉泽尔·黑酿",
    "Knight Davion": "达维安爵士",
    "Mercurial": "莫丘利",
    "Mirana Nightshade": "米拉娜·夜影",
    "Mangix": "曼吉克斯",
    "Raijin Thunderkeg": "雷神·风暴烈酒",
    "Alleria": "奥蕾莉亚",
    "Huskar": "哈斯卡",
    "Lanaya": "拉娜娅",
    "Demnok Lannik": "戴蒙·莱尼克",
    "Puck": "帕克",
    "Vol'Jin": "沃金",
    "Rikimaru": "力丸",
    "Rattletrap": "瑞托崔普",
    "Kunkka": "戴林·普罗德摩尔",
    "Syllabear": "悉拉贝尔",
    "Lina Inverse": "莉娜·茵巴斯",
    "Harbinger": "先兆者",
    "Yurnero": "尤涅若",
    "Medusa": "美杜莎",
    "Meepo": "米波",
    "Balanar": "巴拉那",
    "King Leoric": "李奥瑞克王",
    "Dazzle": "戴泽",
    "Anub'arak": "阿努巴拉克",
    "Azgalor": "阿兹加洛",
    "Slardar": "斯拉达",
    "Akasha": "阿卡莎",
    "Darkterror": "暗惧者",
    "Viper": "蝮蛇",
    "Razor": "剃刀",
    "Black Arachnia": "布蕾克·艾拉齐娜",
    "Leshrac the Malicious": "恶毒的拉席克",
    "Nevermore": "奈文魔尔",
    "Kel'thuzad": "克尔苏加德",
    "Ish'kafel": "依什卡菲尔",
    "Dirge": "挽歌",
    "Nortrom": "诺崇",
    "Mortred": "茉崔蒂",
    "Darchrow": "达克罗",
    "Rooftrellen": "鲁夫特伦",
    "Ulfsaar": "乌尔萨",
    "Aggron Stonebreaker": "阿格隆·碎石者",
    "Boush": "鲍什",
    "Furion": "法里奥",
    "Azwraith": "阿兹瑞斯",
    "Tiny": "小小",
    "Lesale Deathbringer": "里瑟尔·死亡使者",
    "Squee Spleen and Spoon": "斯奎，斯布林和斯布伦",
    "Chen": "陈",
    "Krobelus": "克萝贝露丝",
    "Terrorblade": "恐怖利刃",
    "Magnus": "马格纳斯",
    "Lion": "莱恩",
    "Visage": "维萨吉",
    "Nessaj": "涅沙",
    "Banehallow": "贝恩霍勒",
    "Cairne Bloodhoof": "凯恩·血蹄",
    "Jin'zakk": "金扎卡",
    "Kael": "凯尔",
    "Ezalor": "伊扎洛",
    "N'aix": "奈克斯",
    "Barathrum": "巴拉森",
    "Slark": "斯拉克",
    "Kaldr": "卡尔德",
    "Aurel Vlaicu": "奥雷尔·弗拉伊库",
    "Io": "伊俄",
    "Thrall": "萨尔",
    "Eredar": "艾瑞达",
    "Icarus": "伊卡洛斯",
    "Ymir": "尤弥尔",
    "Rubick": "拉比克",
    "Rizzrak": "瑞兹拉克",
    "Xin": "新",
    "Tresdin": "特斯丁",
    "Dragonus": "扎贡纳斯"
};

var job_translate =
{
    "Vengeful Spirit": "复仇之魂",
    "Lord of Avernus": "地狱领主",
    "Oblivion": "湮灭法师",
    "Sand King": "沙王",
    "Bone Fletcher": "骷髅射手",
    "Moon Rider": "月之骑士",
    "Centaur Warchief": "半人马酋长",
    "Lord of Olympus": "奥林匹斯之王",
    "Enchantress": "魅惑魔女",
    "Morphling": "变体精灵",
    "Dwarven Sniper": "矮人狙击手",
    "Troll Warlord": "巨魔战将",
    "Tidehunter": "潮汐猎人",
    "Shadow Shaman": "暗影萨满",
    "Bane Elemental": "祸乱之源",
    "Necrolyte": "死灵法师",
    "Butcher": "屠夫",
    "Nerubian Weaver": "编织者",
    "Axe": "斧王",
    "Crystal Maiden": "水晶室女",
    "Bloodseeker": "嗜血狂魔",
    "Doom Bringer": "末日使者",
    "Rogue Knight": "流浪剑客",
    "Bristleback": "刚背兽",
    "Naga Siren": "娜迦海妖",
    "Earthshaker": "撼地神牛",
    "Bounty Hunter": "赏金猎人",
    "Anti-Mage": "敌法师",
    "Beastmaster": "兽王",
    "Drow Ranger": "卓尔游侠",
    "Twin Head Dragon": "双头龙",
    "Omniknight": "全能骑士",
    "Alchemist": "炼金术士",
    "Dragon Knight": "龙骑士",
    "Spectre": "幽鬼",
    "Priestess of the Moon": "月之女祭司",
    "Pandaren Brewmaster": "熊猫酒仙",
    "Storm Spirit": "风暴之灵",
    "Windrunner": "风行者",
    "Sacred Warrior": "神灵武士",
    "Templar Assassin": "圣堂刺客",
    "Warlock": "术士",
    "Faerie Dragon": "仙女龙",
    "Witch Doctor": "巫医",
    "Stealth Assassin": "隐形刺客",
    "Clockwerk Goblin": "发条地精",
    "Admiral": "舰队统帅",
    "Lone Druid": "德鲁伊",
    "Slayer": "秀逗魔导士",
    "Obsidian Destroyer": "黑曜毁灭者",
    "Juggernaut": "主宰",
    "Gorgon": "蛇发女妖",
    "Geomancer": "地卜师",
    "Night Stalker": "暗夜魔王",
    "Skeleton King": "骷髅王",
    "Shadow Priest": "暗影牧师",
    "Nerubian Assassin": "地穴刺客",
    "Pit Lord": "深渊领主",
    "Slithereen Guard": "鱼人守卫",
    "Queen of Pain": "痛苦女王",
    "Faceless Void": "虚空假面",
    "Netherdrake": "冥界亚龙",
    "Lightning Revenant": "闪电幽魂",
    "Broodmother": "育母蜘蛛",
    "Tormented Soul": "受折磨的灵魂",
    "Shadow Fiend": "影魔",
    "Lich": "巫妖",
    "Dark Seer": "黑暗贤者",
    "Undying": "不朽尸王",
    "Silencer": "沉默术士",
    "Phantom Assassin": "幻影刺客",
    "Enigma": "谜团",
    "Treant Protector": "树精卫士",
    "Ursa Warrior": "熊战士",
    "Ogre Magi": "食人魔魔法师",
    "Tinker": "地精修补匠",
    "Prophet": "先知",
    "Phantom Lancer": "幻影长矛手",
    "Stone Giant": "山岭巨人",
    "Venomancer": "剧毒术士",
    "Goblin Techies": "地精工程师",
    "Holy Knight": "圣骑士",
    "Death Prophet": "死亡先知",
    "Soul Keeper": "灵魂守卫",
    "Magnataur": "半人猛犸",
    "Demon Witch": "恶魔巫师",
    "Necro'lic": "死灵飞龙",
    "Chaos Knight": "混沌骑士",
    "Lycanthrope": "狼人",
    "Tauren Chieftain": "牛头人酋长",
    "Batrider": "蝙蝠骑士",
    "Invoker": "祈求者",
    "Keeper of the Light": "光之守卫",
    "Lifestealer": "噬魂鬼",
    "Spiritbreaker": "裂魂人",
    "Murloc Nightcrawler": "鱼人夜行者",
    "Ancient Apparition": "极寒幽魂",
    "Gyrocopter": "矮人直升机",
    "Guardian Wisp": "精灵守卫",
    "Disruptor": "干扰者",
    "Shadow Demon": "暗影恶魔",
    "Phoenix": "凤凰",
    "Tuskarr": "巨牙海民",
    "Grand Magus": "大魔导师",
    "Goblin Shredder": "地精撕裂者",
    "Ember Spirit": "灰烬之灵",
    "Legion Commander": "军团指挥官",
    "Skywrath Mage": "天怒法师"
};

var skill_translate =
{
    "Acid Spray": "酸性喷雾",
    "Adaptive Strike": "变体攻击",
    "Aftershock": "余震",
    "Amplify Damage": "伤害加深",
    "Ancestral Spirit": "先祖之魂",
    "Anchor Smash": "锚击",
    "Ancient Seal": "上古封印",
    "Aphotic Shield": "无光之盾",
    "Arc Lightning": "弧形闪电",
    "Arcane Bolt": "奥术箭",
    "Arcane Orb": "奥术天球",
    "Assassinate": "暗杀",
    "Astral Imprisonment": "星体禁锢",
    "Avalanche": "山崩",
    "Backstab": "背刺",
    "Backtrack": "回到过去",
    "Ball Lightning": "球状闪电",
    "Bash": "重击",
    "Battery Assault": "弹幕冲击",
    "Battle Hunger": "战斗饥渴",
    "Battle Trance": "战斗专注",
    "Berserker Rage": "狂战士之怒",
    "Berserker's Blood": "狂战士之血",
    "Berserker's Call": "狂战士的怒吼",
    "Black Hole": "黑洞",
    "Blade Dance": "剑舞",
    "Blade Fury": "剑刃风暴",
    "Blink Strike": "闪烁突袭",
    "Blink": "闪烁",
    "Blood Bath": "屠戮",
    "Bloodlust": "嗜血术",
    "Bloodrage": "血之狂暴",
    "Blur": "模糊",
    "Borrowed Time": "回光返照",
    "Brain Sap": "蚀脑",
    "Breathe Fire": "火焰气息",
    "Brilliance Aura": "辉煌光环",
    "Bristleback": "刚毛后背",
    "Burning Spear": "沸血之矛",
    "Burrowstrike": "掘地穿刺",
    "Call Down": "召唤飞弹",
    "Call of the Wild": "野性呼唤",
    "Carrion Swarm": "食腐蝠群",
    "Caustic Finale": "腐尸毒",
    "Chain Frost": "连环霜冻",
    "Chakra Magic": "查克拉魔法",
    "Chakram": "锯齿飞轮",
    "Chaos Bolt": "混乱之箭",
    "Charge of Darkness": "暗影冲刺",
    "Chemical Rage": "化学狂暴",
    "Chilling Touch": "寒冰之触",
    "Chronosphere": "时间结界",
    "Cold Feet": "寒霜之足",
    "Command Aura": "命令光环",
    "Concussive Shot": "震荡射击",
    "Corrosive Skin": "腐蚀外表",
    "Counter Helix": "反击螺旋",
    "Coup de Grace": "恩赐解脱",
    "Craggy Exterior": "崎岖外表",
    "Crippling Fear": "伤残恐惧",
    "Critical Strike": "致命一击",
    "Crystal Nova": "水晶新星",
    "Culling Blade": "淘汰之刃",
    "Curse of the Silent": "静默诅咒",
    "Dark Pact": "黑暗契约",
    "Dark Rift": "黑暗之门",
    "Dark Ritual": "邪恶祭祀",
    "Darkness": "黑暗时间",
    "Death Coil": "死亡缠绕",
    "Death Pact": "死亡契约",
    "Death Pulse": "死亡脉冲",
    "Death Ward": "死亡守卫",
    "Decay": "腐朽",
    "Decrepify": "衰老",
    "Degen Aura": "退化光环",
    "Demonic Conversion": "恶魔转化",
    "Demonic Purge": "邪恶净化",
    "Desolate": "荒芜",
    "Devour": "吞噬",
    "Diabolic Edict": "恶魔赦令",
    "Dismember": "肢解",
    "Dispersion": "折射",
    "Disruption": "崩裂禁锢",
    "Divided We Stand": "分则能成",
    "Doom": "末日",
    "Doppelwalk": "神出鬼没",
    "Double Edge": "双刃剑",
    "Dragon Blood": "龙族血统",
    "Dragon Slave": "龙破斩",
    "Dragon Tail": "神龙摆尾",
    "Dream Coil": "梦境缠绕",
    "Drunken Brawler": "醉拳",
    "Drunken Haze": "醉酒云雾",
    "Dual Breath": "冰火交加",
    "Duel": "决斗",
    "Earth Splitter": "裂地者",
    "Earthbind": "地之束缚",
    "Earthshock": "震撼大地",
    "Echo Slam": "回音击",
    "Echo Stomp": "回音重踏",
    "Eclipse": "月蚀",
    "Elder Dragon Form": "真龙形态",
    "Electric Vortex": "电子涡流",
    "Elune's Arrow": "月神之箭",
    "Empower": "授予力量",
    "Empowering Haste": "神行太保",
    "Enchant Totem": "强化图腾",
    "Enchant": "魅惑",
    "Enfeeble": "虚弱",
    "Enrage": "激怒",
    "Ensnare": "诱捕",
    "Epicenter": "地震",
    "Essence Aura": "精气光环",
    "Essence Shift": "能量转移",
    "Ether Shock": "苍穹震击",
    "Exorcism": "驱使恶灵",
    "Exort": "火",
    "Expulsion": "尸爆",
    "Eye of the Storm": "风暴之眼",
    "Fade Bolt": "弱化能流",
    "Fatal Bonds": "致命连接",
    "Feast": "盛宴",
    "Feral Impulse": "野性驱使",
    "Fervor": "热血战魂",
    "Fiend's Grip": "恶魔的掌控",
    "Fiery Soul": "炽魂",
    "Finger of Death": "死亡一指",
    "Fire Remnant": "火之余烬",
    "Fire Spirits": "烈火精灵",
    "Fireblast": "火焰爆轰",
    "Firefly": "火焰飞行",
    "Firestorm": "火焰风暴",
    "Fissure": "沟壑",
    "Flak Cannon": "高射火炮",
    "Flame Guard": "火焰壁垒",
    "Flamebreak": "烈焰破击",
    "Flaming Lasso": "燃烧枷锁",
    "Flesh Golem": "血肉傀儡",
    "Flesh Heap": "堆积腐肉",
    "Focus Fire": "集中火力",
    "Force of Nature": "自然之力",
    "Freezing Field": "极寒领域",
    "Frost Armor": "霜冻护甲",
    "Frost Arrows": "霜冻之箭",
    "Frost Nova": "霜冻新星",
    "Frostbite": "冰封禁制",
    "Frostmourne": "霜之哀伤",
    "Frozen Sigil": "冰封魔印",
    "Fury Swipes": "怒意狂击",
    "Geminate Attack": "连击",
    "Geostrike": "地之突袭",
    "Ghost Ship": "幽灵船",
    "Glaives of Wisdom": "智慧之刃",
    "Glimpse": "恶念瞥视",
    "Global Silence": "全领域静默",
    "Goblin's Greed": "地精的贪婪",
    "God's Strength": "神之力量",
    "Grave Chill": "黄泉颤抖",
    "Gravekeeper's Cloak": "守墓人的斗篷",
    "Great Cleave": "巨力挥舞",
    "Great Fortitude": "刚毅不屈",
    "Greater Bash": "巨力重击",
    "Grow!": "长大！",
    "Guardian Angel": "守护天使",
    "Gush": "巨浪",
    "Hand of God": "上帝之手",
    "Haunt": "鬼影重重",
    "Headshot": "爆头",
    "Healing Ward": "治疗守卫",
    "Heartstopper Aura": "竭心光环",
    "Heat Seeking Missile": "热导飞弹",
    "Hellfire Blast": "冥火爆击",
    "Holy Persuasion": "神圣劝化",
    "Homing Missile": "追踪导弹",
    "Hoof Stomp": "马蹄践踏",
    "Hookshot": "发射钩爪",
    "Howl": "嚎叫",
    "Hunter in the Night": "夜晚中的狩猎者",
    "Icarus Dive": "凤凰冲击",
    "Ice Blast": "冰晶爆轰",
    "Ice Path": "冰封路径",
    "Ice Shards": "寒冰片",
    "Ice Vortex": "冰霜漩涡",
    "Ignite": "引燃",
    "Illuminate": "冲击波",
    "Illusory Orb": "幻象法球",
    "Impale": "穿刺",
    "Impetus": "推进",
    "Incapacitating Bite": "麻痹之咬",
    "Infest": "感染",
    "Inner Beast": "野性之心",
    "Inner Vitality": "活血术",
    "Insatiable Hunger": "极度饥渴",
    "Invoke": "元素祈唤",
    "Ion Shell": "离子外壳",
    "Jinada": "忍术",
    "Juxtapose": "并列",
    "Kinetic Field": "动能力场",
    "Kraken Shell": "海妖外壳",
    "Laguna Blade": "神灭斩",
    "Land Mines": "埋布地雷",
    "Laser": "激光",
    "Last Word": "遗言",
    "Leap": "跳跃",
    "Leech Seed": "寄生种子",
    "Life Break": "牺牲",
    "Life Drain": "生命汲取",
    "Light Strike Array": "光击阵",
    "Lightning Bolt": "雷击",
    "Lightning Storm": "闪电风暴",
    "Liquid Fire": "液态火",
    "Living Armor": "活体护甲",
    "Lucent Beam": "月光",
    "Lunar Blessing": "月之祝福",
    "LVL? Death": "死亡",
    "Macropyre": "烈焰焚身",
    "Magic Missile": "魔法箭",
    "Maledict": "诅咒",
    "Malefice": "憎恶",
    "Mana Break": "发力损毁",
    "Mana Burn": "法力燃烧",
    "Mana Drain": "法力汲取",
    "Mana Leak": "法力流失",
    "Mana Shield": "魔法护盾",
    "Mana Void": "法力虚空",
    "March of the Machines": "机器人的进军",
    "Marksmanship": "射手天赋",
    "Mass Serpent Ward": "群蛇守卫",
    "Meat Hook": "肉钩",
    "Meld": "隐匿",
    "Metamorphosis": "变身",
    "Midnight Pulse": "午夜凋零",
    "Mirror Image": "镜像",
    "Moment of Courage": "勇气之霎",
    "Moon Glaive": "月刃",
    "Moonlight Shadow": "月之暗面",
    "Morph": "属性转换",
    "Multi Cast": "多重施法",
    "Mystic Flare": "神秘之耀",
    "Mystic Snake": "秘术异蛇",
    "Natural Order": "自然秩序",
    "Nature's Attendants": "自然之助",
    "Nature's Guise": "大自然的掩护",
    "Necromastery": "支配死灵",
    "Nether Blast": "幽冥爆轰",
    "Nether Strike": "幽冥一击",
    "Nether Swap": "移形换位",
    "Nether Ward": "幽冥守卫",
    "Nethertoxin": "幽冥剧毒",
    "Nightmare": "噩梦",
    "Null Field": "失效力场",
    "Omnislash": "无敌斩",
    "Open Wounds": "撕裂伤口",
    "Overcharge": "过载",
    "Overgrowth": "疯狂生长",
    "Overload": "超负荷",
    "Overpower": "超强力量",
    "Overwhelming Odds": "压倒性优势",
    "Paralyzing Cask": "麻痹药剂",
    "Penitence": "赎罪",
    "Permanent Invisibility": "永久隐身",
    "Phantasm": "幻象",
    "Phantom Edge": "幻化之锋",
    "Phantom Strike": "幻影突袭",
    "Phase Shift": "相位转移",
    "Pit of Malice": "怨念深渊",
    "Plague Ward": "瘟疫守卫",
    "Plasma Field": "等离子场",
    "Poison Attack": "毒性攻击",
    "Poison Nova": "剧毒新星",
    "Poison Sting": "毒刺",
    "Poison Touch": "剧毒之触",
    "Poof": "忽悠",
    "Pounce": "突袭",
    "Power Cogs": "能量齿轮",
    "Powershot": "强力击",
    "Presence of the Dark Lord": "魔王降临",
    "Press The Attack": "强攻",
    "Primal Roar": "原始咆哮",
    "Primal Split": "元素分离",
    "Psi Blades": "灵能之刃",
    "Psionic Trap": "灵能陷阱",
    "Pulse Nova": "脉冲新星",
    "Purification": "洗礼",
    "Quas": "冰",
    "Quill Spray": "针刺扫射",
    "Rabid": "狂猛",
    "Rage": "狂暴",
    "Rain of Chaos": "混乱之雨",
    "Ravage": "毁灭",
    "Reactive Armor": "活性护甲",
    "Reality Rift": "实相裂隙",
    "Reaper's Scythe": "死神镰刀",
    "Rearm": "再装填",
    "Reflection": "倒影",
    "Refraction": "折光",
    "Reincarnation": "重生",
    "Relocate": "守卫降临",
    "Remote Mines": "遥控炸弹",
    "Repel": "驱逐",
    "Replicate": "复制",
    "Requiem of Souls": "魂之挽歌",
    "Return": "反击",
    "Reverse Polarity": "两级反转",
    "Rip Tide": "激流",
    "Rocket Barrage": "火箭弹幕",
    "Rocket Flare": "照明火箭",
    "Rot": "腐烂",
    "Rupture": "割裂",
    "Sadist": "施虐之心",
    "Sand Storm": "沙尘暴",
    "Sanity's Eclipse": "神智之蚀",
    "Scorched Earth": "焦土",
    "Scream of Pain": "痛苦尖叫",
    "Searing Arrows": "灼热之箭",
    "Searing Chains": "烧灼锁链",
    "Shackles": "枷锁",
    "Shackleshot": "束缚击",
    "Shadow Dance": "暗影之舞",
    "Shadow Poison": "暗影剧毒",
    "Shadow Strike": "暗影突袭",
    "Shadow Wave": "暗影波",
    "Shadow Word": "暗言术",
    "Shadowraze": "毁灭阴影",
    "Shallow Grave": "薄葬(G)",
    "Shapeshift": "变狼",
    "Shockwave": "震荡波",
    "Shrapnel": "榴霰弹",
    "Shukuchi": "缩地",
    "Shuriken Toss": "投掷飞镖",
    "Silence": "沉默魔法",
    "Skewer": "獠牙冲刺",
    "Sleight of Fist": "无影拳",
    "Slithereen Crush": "鱼人碎击",
    "Smoke Screen": "烟幕",
    "Snowball": "雪球",
    "Song of the Siren": "海妖之歌",
    "Sonic Wave": "超声冲击波",
    "Soul Assumption": "灵魂超度",
    "Soul Catcher": "灵魂猎手",
    "Soul Rip": "噬魂",
    "Spawn Spiderlings": "孵化蜘蛛",
    "Spectral Dagger": "幽鬼之刃",
    "Spell Shield": "法术护盾",
    "Spell Steal": "技能窃取",
    "Spiked Carapace": "尖刺外壳",
    "Spin Web": "织网",
    "Spirit Form": "灵魂形态",
    "Spirit Lance": "灵魂之矛",
    "Spirits": "幽光之魂",
    "Split Earth": "撕裂大地",
    "Split Shot": "分裂箭",
    "Sprint": "冲刺",
    "Sprout": "发芽",
    "Starfall": "群星坠落",
    "Stasis Trap": "麻痹陷阱",
    "Static Field": "静电场",
    "Static Link": "静电链接",
    "Static Remnant": "残影",
    "Static Storm": "静态风暴",
    "Sticky Napalm": "黏性燃油",
    "Stifling Dagger": "窒息之刃",
    "Stone Gaze": "石化凝视",
    "Storm Bolt": "风暴之锤",
    "Strafe": "扫射",
    "Strygwyr's Thirst": "嗜血渴望",
    "Suicide Squad, Attack!": "自杀攻击",
    "Summon Familiars": "召唤佣兽",
    "Summon Spirit Bear": "熊灵伙伴",
    "Summon Wolves": "召狼",
    "Sun Ray": "烈日炙烤",
    "Sunder": "灵魂隔断",
    "Supernova": "超级新星",
    "Surge": "奔腾",
    "Synergy": "协同",
    "Take Aim": "瞄准",
    "Telekinesis": "隔空取物",
    "Teleportation": "传送",
    "Test of Faith": "忠诚考验",
    "Tether": "闪电之链",
    "The Swarm": "蝗虫群",
    "Thunder Clap": "雷霆一击",
    "Thunder Strike": "雷霆之击",
    "Thundergod's Wrath": "雷神之怒",
    "Tidebringer": "潮汐使者",
    "Timber Chain": "伐木锯链",
    "Time Lapse": "时光倒流",
    "Time Lock": "时间锁定",
    "Time Walk": "时间漫游",
    "Tombstone": "墓碑",
    "Torrent": "洪流",
    "Toss": "投掷",
    "Track": "追踪术",
    "True Form": "变形术",
    "Trueshot Aura": "强击光环",
    "Unstable Concoction": "不稳定化合物",
    "Unstable Current": "不稳定电流",
    "Untouchable": "不可侵犯",
    "Upheaval": "剧变",
    "Vacuum": "真空",
    "Vampiric Aura": "吸血光环",
    "Vendetta": "复仇",
    "Venomous Gale": "瘴气",
    "Viper Strike": "蝮蛇突袭",
    "Viscous Nasal Goo": "粘稠鼻液",
    "Void": "虚空",
    "Voodoo Restoration": "巫毒回复术",
    "Voodoo": "妖术",
    "Wall of Replica": "复制之墙",
    "Walrus Punch": "海象挥击",
    "Waning Rift": "新月之痕",
    "Warcry": "战吼",
    "Warpath": "战意",
    "Wave of Terror": "恐怖波动",
    "Waveform": "波浪形态",
    "Weave": "编织",
    "Wex": "雷",
    "Whirling Axes": "旋风飞斧",
    "Whirling Death": "死亡旋风",
    "Wild Axes": "野性之斧",
    "Wind Walk": "疾风步",
    "Windrunner": "风行者",
    "Witchcraft": "巫术精研",
    "Wrath of Nature": "自然之怒",
    "X Marks The Spot": "X 标记",
    "Zeal": "狂热"
};
