rem Build folder structure for my data.

mkdir "Data\Microsoft\Help Library"
mkdir "Data\Microsoft\Windows"
mkdir "Design\Adobe Illustrator"
mkdir "Design\Adobe Photoshop"
mkdir "Design\Autodesk 3ds Max"
mkdir "Development\Sources"
mkdir "Softwares\Archived\Development"
mkdir "Softwares\Archived\Games"
mkdir "Softwares\Archived\Media"
mkdir "Softwares\Archived\Tools"
mkdir "Softwares\Common"
mkdir "Softwares\Drivers"
mkdir "Softwares\Enterprise\Adobe"
mkdir "Softwares\Enterprise\Autodesk"
mkdir "Softwares\Enterprise\Microsoft"
mkdir "Temp\Visual C++ Data Cache"
mkdir "Temp\Visual Studio Debug Symbol Cache"
