#pragma once

#include "WindowsGUILibraryBase.h"

enum class SystemColorIndex : int
{
    Scrollbar = COLOR_SCROLLBAR,
    Background = COLOR_BACKGROUND,
    ActiveCaption = COLOR_ACTIVECAPTION,
    InactiveCaption = COLOR_INACTIVECAPTION,
    Menu = COLOR_MENU,
    Window = COLOR_WINDOW,
    WindowFrame = COLOR_WINDOWFRAME,
    MenuText = COLOR_MENUTEXT,
    WindowText = COLOR_WINDOWTEXT,
    CaptionText = COLOR_CAPTIONTEXT,
    ActiveBorder = COLOR_ACTIVEBORDER,
    InactiveBorder = COLOR_INACTIVEBORDER,
    AppWorkspace = COLOR_APPWORKSPACE,
    Highlight = COLOR_HIGHLIGHT,
    HighlightText = COLOR_HIGHLIGHTTEXT,
    BtnFace = COLOR_BTNFACE,
    BtnShadow = COLOR_BTNSHADOW,
    GrayText = COLOR_GRAYTEXT,
    BtnText = COLOR_BTNTEXT,
    InactiveCaptiontext = COLOR_INACTIVECAPTIONTEXT,
    BtnHighlight = COLOR_BTNHIGHLIGHT,
    ThreeDDkShadow = COLOR_3DDKSHADOW,
    ThreeDLight = COLOR_3DLIGHT,
    InfoText = COLOR_INFOTEXT,
    InfoBk = COLOR_INFOBK,
    Hotlight = COLOR_HOTLIGHT,
    GradientActiveCaption = COLOR_GRADIENTACTIVECAPTION,
    GradientInactiveCaption = COLOR_GRADIENTINACTIVECAPTION,
    MenuHilight = COLOR_MENUHILIGHT,
    Menubar = COLOR_MENUBAR,
    Desktop = COLOR_DESKTOP,
    ThreeDFace = COLOR_3DFACE,
    ThreeDShadow = COLOR_3DSHADOW,
    ThreeDHighlight = COLOR_3DHIGHLIGHT,
    ThreeDHilight = COLOR_3DHILIGHT,
    BtnHilight = COLOR_BTNHILIGHT,
};
