#pragma once

namespace DirectWriteWrapper
{
    public enum class InformationalStringId
    {
        None = DWRITE_INFORMATIONAL_STRING_NONE,
        CopyrightNotice = DWRITE_INFORMATIONAL_STRING_COPYRIGHT_NOTICE,
        VersionStrings = DWRITE_INFORMATIONAL_STRING_VERSION_STRINGS,
        Trademark = DWRITE_INFORMATIONAL_STRING_TRADEMARK,
        Manufacturer = DWRITE_INFORMATIONAL_STRING_MANUFACTURER,
        Designer = DWRITE_INFORMATIONAL_STRING_DESIGNER,
        DesignerUrl = DWRITE_INFORMATIONAL_STRING_DESIGNER_URL,
        Description = DWRITE_INFORMATIONAL_STRING_DESCRIPTION,
        FontVendorUrl = DWRITE_INFORMATIONAL_STRING_FONT_VENDOR_URL,
        LicenseDescription = DWRITE_INFORMATIONAL_STRING_LICENSE_DESCRIPTION,
        LicenseInfoUrl = DWRITE_INFORMATIONAL_STRING_LICENSE_INFO_URL,
        Win32FamilyNames = DWRITE_INFORMATIONAL_STRING_WIN32_FAMILY_NAMES,
        Win32SubfamilyNames = DWRITE_INFORMATIONAL_STRING_WIN32_SUBFAMILY_NAMES,
        PreferredFamilyNames = DWRITE_INFORMATIONAL_STRING_PREFERRED_FAMILY_NAMES,
        PreferredSubfamilyNames = DWRITE_INFORMATIONAL_STRING_PREFERRED_SUBFAMILY_NAMES,
        SampleText = DWRITE_INFORMATIONAL_STRING_SAMPLE_TEXT,
        FullName = DWRITE_INFORMATIONAL_STRING_FULL_NAME,
        PostScriptName = DWRITE_INFORMATIONAL_STRING_POSTSCRIPT_NAME,
        PostScriptCidName = DWRITE_INFORMATIONAL_STRING_POSTSCRIPT_CID_NAME
    };
}
